apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
  namespace: book-store-ns
  labels:
    app: book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - name: book-container
          image: rutasd/a3_book_service:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /status
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10