apiVersion: v1
kind: Service
metadata:
  name: book
  namespace: book-store-ns
  labels:
    app: book
spec:
  selector:
    app: book
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP