apiVersion: v1
kind: Service
metadata:
  name: book-bff
  namespace: book-store-ns
  labels:
    app: book-bff
spec:
  selector:
    app: book-bff
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer