apiVersion: v1
kind: Service
metadata:
  name: crm-service
  namespace: book-store-ns
  labels:
    app: crm-service
spec:
  selector:
    app: crm-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP