apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  namespace: book-store-ns
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer-container
          image: rutasd/a3_cust_service:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /status
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10