apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: book-store-ns
  labels:
    app: customer
spec:
  selector:
    app: customer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP